// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvw9vl4rYj6jwt121sZwBim-ltQ_4v6M',
    appId: '1:507816911201:web:b8b70853ac9c3348ee2520',
    messagingSenderId: '507816911201',
    projectId: 'quizapp-35de4',
    authDomain: 'quizapp-35de4.firebaseapp.com',
    storageBucket: 'quizapp-35de4.firebasestorage.app',
    measurementId: 'G-E2Y2CMJGNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyciTy37Ikni0mMy4AEDHzJtbno_F0Jw8',
    appId: '1:507816911201:android:5faa577b7a75e8ebee2520',
    messagingSenderId: '507816911201',
    projectId: 'quizapp-35de4',
    storageBucket: 'quizapp-35de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkixPAWCmadsRdDQ6eNbcpEOSYHF1NBPw',
    appId: '1:507816911201:ios:57a03519cff38efdee2520',
    messagingSenderId: '507816911201',
    projectId: 'quizapp-35de4',
    storageBucket: 'quizapp-35de4.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkixPAWCmadsRdDQ6eNbcpEOSYHF1NBPw',
    appId: '1:507816911201:ios:57a03519cff38efdee2520',
    messagingSenderId: '507816911201',
    projectId: 'quizapp-35de4',
    storageBucket: 'quizapp-35de4.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzvw9vl4rYj6jwt121sZwBim-ltQ_4v6M',
    appId: '1:507816911201:web:e1bb263d5ab3b7faee2520',
    messagingSenderId: '507816911201',
    projectId: 'quizapp-35de4',
    authDomain: 'quizapp-35de4.firebaseapp.com',
    storageBucket: 'quizapp-35de4.firebasestorage.app',
    measurementId: 'G-12X796T7G5',
  );
}
